Repository webkom/lego, pull requests merged in 2022-10, with the labels that each got.

#2980 Store additional comments from interest form
  lego/apps/companies/migrations/0026_rename_second_comment_companyinterest_other_event_comment_and_more.py
  lego/apps/companies/models.py
  lego/apps/companies/serializers.py
  lego/apps/companies/templates/companies/email/response_mail_bedkom.html
  lego/apps/companies/templates/companies/email/response_mail_bedkom.txt
  lego/settings/lego.py
Labels: new-feature, approved, small-fix

#3017 Corrected README.md
  README.md
Labels: approved, ready-to-merge, small-fix

#3015 Add board and revue to public groups
  lego/apps/users/constants.py
Labels: approved, small-fix

#3020 Remove incorrect comma -> tuple
  lego/apps/surveys/models.py
Labels: priority:high, bug-fix, review-needed, ready-to-merge, small-fix

#3012 Attatch users' photo consents on event & make sure consent for event exists before registration
  lego/apps/events/serializers/events.py
  lego/apps/events/tests/test_events_api.py
  lego/apps/users/models.py
  lego/apps/users/serializers/users.py
  lego/apps/users/tests/test_models.py
Labels: approved, bug-fix, ready-to-merge

#3024 Create new photo consents for not-open pools
  lego/apps/events/serializers/events.py
  lego/apps/events/tests/test_events_api.py
Labels: approved, bug-fix, ready-to-merge, small-fix

#3034 Add nestledere group to LDAP sync
  lego/settings/lego.py
Labels: approved, ready-to-merge, flawless

#3013 Change default captcha key and verification site
  lego/settings/base.py
  lego/settings/development.py
Labels: review-needed, small-fix

#3033 Fix hard coded groups
  lego/apps/users/action_handlers.py
  lego/apps/users/permissions.py
  lego/apps/users/views/membership_history.py
Labels: approved, small-fix

#3046 Fix return of consent for admitted users & users on waiting list
  lego/apps/events/models.py
  lego/apps/events/serializers/events.py
  lego/apps/events/tests/test_events_api.py
  lego/apps/events/views.py
Labels: priority:high, approved, bug-fix, ready-to-merge
