Repository webkom/lego, pull requests merged in 2022-08, with the labels that each got.

#2805 Fix all deprecated stuff
  lego/api/test_urls.py
  lego/api/tests/test_docs.py
  lego/apps/articles/views.py
  lego/apps/companies/views.py
  lego/apps/contact/tests/test_views.py
  lego/apps/email/tests/test_views.py
  lego/apps/email/views.py
  lego/apps/events/tests/test_event_methods.py
  lego/apps/events/tests/test_events_api.py
  lego/apps/events/tests/test_webhooks.py
  lego/apps/events/views.py
  lego/apps/feeds/views.py
  lego/apps/followers/tests/test_views.py
  lego/apps/followers/views.py
  lego/apps/frontpage/tests.py
  lego/apps/gallery/views.py
  lego/apps/joblistings/views.py
  lego/apps/meetings/fixtures/development_meetings.yaml
  lego/apps/meetings/fixtures/test_meetings.yaml
  lego/apps/meetings/views.py
  lego/apps/notifications/tests/test_models.py
  lego/apps/notifications/tests/test_views.py
  lego/apps/notifications/views.py
  lego/apps/oauth/views.py
  lego/apps/quotes/tests/test_api_quotes.py
  lego/apps/quotes/views.py
  lego/apps/restricted/tests/test_message.py
  lego/apps/restricted/tests/test_parser.py
  lego/apps/restricted/tests/test_processor.py
  lego/apps/restricted/tests/test_utils.py
  lego/apps/restricted/tests/test_views.py
  lego/apps/restricted/views.py
  lego/apps/surveys/tests/test_submissions_api.py
  lego/apps/surveys/tests/test_surveys_api.py
  lego/apps/surveys/tests/test_templates_api.py
  lego/apps/surveys/views.py
  lego/apps/tags/tests/test_api.py
  lego/apps/users/tests/test_abakusgroup_api.py
  lego/apps/users/tests/test_grade_bump.py
  lego/apps/users/tests/test_membership_history.py
  lego/apps/users/tests/test_password_change.py
  lego/apps/users/tests/test_users_api.py
  lego/apps/users/views/abakus_groups.py
  lego/apps/users/views/membership_history.py
  lego/apps/users/views/memberships.py
  lego/apps/users/views/penalties.py
  lego/apps/users/views/student_confirmation.py
  lego/utils/test_utils.py
  lego/utils/tests/test_content_types.py
  lego/utils/tests/test_renderers.py
  lego/utils/tests/test_views.py
Labels: enhancement, approved, ready-to-merge

#2829 Change wording of student confirmation email
  lego/apps/users/templates/users/email/student_confirmation.html
  lego/apps/users/templates/users/email/student_confirmation.txt
  lego/apps/users/views/student_confirmation.py
Labels: enhancement, approved, ready-to-merge, small-fix

#2830 Fix make commands by changing python image
  Makefile
Labels: bug-fix, ready-to-merge, small-fix, flawless

#2840 Add a few additional categories for flatpages
  lego/apps/flatpages/constants.py
  lego/apps/flatpages/migrations/0010_alter_page_category.py
Labels: approved, ready-to-merge, small-fix

#2801 Support Django 4
  .github/dependabot.yml
  README.md
  lego/api/tests/test_authentication.py
  lego/api/urls.py
  lego/apps/articles/migrations/0010_alter_article_can_edit_groups_and_more.py
  lego/apps/comments/migrations/0008_alter_comment_created_by_alter_comment_updated_by.py
  lego/apps/companies/migrations/0024_alter_company_created_by_alter_company_updated_by_and_more.py
  lego/apps/emojis/migrations/0002_alter_emoji_created_by_alter_emoji_updated_by.py
  lego/apps/events/migrations/0033_alter_event_can_edit_groups_and_more.py
  lego/apps/events/notifications.py
  lego/apps/events/serializers/registrations.py
  lego/apps/flatpages/migrations/0011_alter_page_can_edit_groups_alter_page_can_edit_users_and_more.py
  lego/apps/gallery/migrations/0008_alter_gallery_can_edit_groups_and_more.py
  lego/apps/joblistings/migrations/0009_alter_joblisting_created_by_and_more.py
  lego/apps/jwt/handlers.py
  lego/apps/meetings/migrations/0009_alter_meeting_created_by_alter_meeting_updated_by_and_more.py
  lego/apps/meetings/notifications.py
  lego/apps/notifications/migrations/0012_alter_announcement_created_by_and_more.py
  lego/apps/oauth/migrations/0003_alter_apiapplication_user.py
  lego/apps/oauth/urls.py
  lego/apps/permissions/tests/migrations/0002_alter_testmodel_can_edit_groups_and_more.py
  lego/apps/permissions/tests/migrations/0002_auto_20170903_2224.py
  lego/apps/podcasts/migrations/0006_alter_podcast_created_by_alter_podcast_updated_by.py
  lego/apps/polls/migrations/0003_alter_option_created_by_alter_option_updated_by_and_more.py
  lego/apps/quotes/migrations/0007_alter_quote_created_by_alter_quote_updated_by.py
  lego/apps/reactions/migrations/0005_alter_reaction_created_by_alter_reaction_updated_by.py
  lego/apps/restricted/migrations/0005_alter_restrictedmail_created_by_and_more.py
  lego/apps/surveys/migrations/0010_alter_answer_created_by_alter_answer_updated_by_and_more.py
  lego/apps/users/migrations/0034_alter_membership_created_by_and_more.py
  lego/apps/websockets/routing.py
  lego/settings/base.py
  lego/settings/development.py
  lego/settings/rest_framework.py
  lego/settings/test.py
  lego/urls.py
  lego/utils/test_utils.py
  requirements/base.txt
  requirements/dev.txt
  requirements/mypy.txt
  requirements/test.txt
  tox.ini
Labels: testing-needed, dependencies, approved, future-is-now, ready-to-merge

#2859 Fix method to retrieve jwt token
  lego/apps/websockets/auth.py
  lego/settings/logging.py
Labels: priority:high, approved, bug-fix, ready-to-merge, small-fix

#2359 Add group view restrictions for events
  lego/apps/events/fixtures/test_events.yaml
  lego/apps/events/models.py
  lego/apps/events/serializers/events.py
  lego/apps/events/tests/test_events_api.py
  lego/apps/events/views.py
  lego/apps/ical/tests/test_api.py
  lego/apps/users/serializers/abakus_groups.py
Labels: help-wanted, new-feature, approved, ready-to-merge, need-before-2050

#2864 Add objectpermission fields to event detail serializer
  lego/apps/events/serializers/events.py
  lego/apps/events/serializers/pools.py
Labels: priority:high, approved, bug-fix, small-fix

#2881 Allow period in student usernames
  lego/apps/users/migrations/0035_alter_user_student_username.py
  lego/apps/users/models.py
  lego/apps/users/serializers/student_confirmation.py
  lego/apps/users/tests/test_student_confirmation_api.py
  lego/apps/users/validators.py
Labels: bug, priority:high, review-needed, small-fix

#2884 Filter on meeting `invitations` instead of `invited_users`
  lego/apps/meetings/tasks.py
Labels: priority:high, bug-fix, review-needed, small-fix

#2886 Return group type from AbakusGroup field
  lego/apps/events/fixtures/development_events.yaml
  lego/apps/users/fields.py
Labels: approved, bug-fix, ready-to-merge, small-fix

#1979 Add Backend Support for Improved Photo Consents
  lego/api/v1.py
  lego/apps/events/constants.py
  lego/apps/events/exceptions.py
  lego/apps/events/fields.py
  lego/apps/events/fixtures/development_events.yaml
  lego/apps/events/fixtures/development_registrations.yaml
  lego/apps/events/migrations/0035_rename_photo_consent_registration_legacy_photo_consent.py
  lego/apps/events/models.py
  lego/apps/events/serializers/registrations.py
  lego/apps/events/tests/test_registrations.py
  lego/apps/events/views.py
  lego/apps/users/constants.py
  lego/apps/users/fixtures/development_photo_consents.yaml
  lego/apps/users/migrations/0035_photoconsent.py
  lego/apps/users/models.py
  lego/apps/users/serializers/photo_consents.py
  lego/apps/users/serializers/users.py
  lego/apps/users/tests/test_models.py
  lego/apps/users/tests/test_users_api.py
  lego/apps/users/views/users.py
  lego/utils/management/commands/load_fixtures.py
Labels: new-feature, testing-needed, changes-requested, review-needed, need-before-2050

#2898 Fix how we compare dates when filtering meetings
  lego/apps/meetings/tasks.py
Labels: bug-fix, review-needed, small-fix

#2879 Make sure meeting object permissions are checked in search
  lego/apps/meetings/permissions.py
Labels: priority:high, security, bug-fix, future-was-2-years-ago, review-needed, small-fix
