Repository webkom/lego, pull requests merged in 2022-11, with the labels that each got.

#3053 Add utm tags to registration reminder links
  lego/apps/followers/templates/followers/email/reminder.html
Labels: approved, small-fix

#2979 Weekly email
  lego/apps/articles/fixtures/test_articles.yaml
  lego/apps/email/tasks.py
  lego/apps/email/templates/email/email/weekly_mail.html
  lego/apps/email/templates/email/email/weekly_mail.txt
  lego/apps/email/tests/test_weekly_email.py
  lego/apps/events/constants.py
  lego/apps/events/fixtures/test_events.yaml
  lego/apps/events/tests/test_events_api.py
  lego/apps/joblistings/constants.py
  lego/apps/joblistings/fixtures/test_joblistings.yaml
  lego/apps/joblistings/models.py
  lego/apps/notifications/constants.py
  lego/apps/notifications/fixtures/test_notification_settings.yaml
  lego/apps/notifications/migrations/0014_alter_notificationsetting_notification_type.py
  lego/apps/notifications/tests/test_views.py
  lego/apps/users/fixtures/test_abakus_groups.py
  lego/apps/users/fixtures/test_abakus_groups.yaml
  lego/apps/users/fixtures/test_users.yaml
  lego/settings/celery.py
Labels: new-feature, approved, review-needed

#3069 Add Bankkom to fixtures, regenerate group-fixtures
  lego/apps/files/fixtures/initial_files.yaml
  lego/apps/tags/fixtures/initial_tags.yaml
  lego/apps/users/fixtures/initial_abakus_groups.py
  lego/apps/users/fixtures/initial_abakus_groups.yaml
Labels: approved, ready-to-merge, small-fix

#3081 Make not-accepted meetings transparent in calendar
  lego/apps/ical/utils.py
  lego/apps/ical/viewsets.py
Labels: enhancement, review-needed, small-fix

#3080 Lock pools as well as event when bumping
  lego/apps/events/fixtures/test_events.yaml
  lego/apps/events/models.py
  lego/apps/events/tasks.py
Labels: testing-needed, priority:high, bug-fix, review-needed

#3087 Enforce Python 3.11 🚄
  .drone.yml
  Dockerfile
  Makefile
  README.md
  setup.cfg
  tox.ini
Labels: testing-needed, approved, future-is-now, ready-to-merge, flawless

#3089 Bump mypy to version 0.991
  lego/apps/companies/views.py
  lego/apps/events/models.py
  lego/apps/events/serializers/registrations.py
  lego/apps/events/tasks.py
  lego/apps/events/views.py
  lego/apps/ical/tests/test_api.py
  lego/apps/notifications/views.py
  lego/apps/tags/validators.py
  lego/apps/tags/views.py
  lego/apps/users/models.py
  lego/settings/celery.py
  lego/urls.py
  lego/utils/tasks.py
  lego/utils/types.py
  requirements/mypy.txt
  setup.cfg
  sitecustomize.py
Labels: enhancement, dependencies, approved, ready-to-merge, types
