Repository webkom/lego, pull requests merged in 2022-09, with the labels that each got.

#2902 Add unique_together constraint on photo consents
  lego/apps/users/migrations/0037_alter_photoconsent_options_and_more.py
  lego/apps/users/models.py
  lego/apps/users/serializers/photo_consents.py
  lego/apps/users/views/users.py
Labels: priority:high, approved, bug-fix, ready-to-merge

#2915 Optimize photo_consents queries on administrate endpoint
  lego/apps/events/fields.py
  lego/apps/events/fixtures/test_events.yaml
  lego/apps/events/models.py
  lego/apps/events/serializers/registrations.py
  lego/apps/events/views.py
  lego/apps/users/models.py
  lego/apps/users/serializers/users.py
Labels: enhancement, review-needed

#2962 Add created_after filtering for joblistings
  lego/apps/companies/serializers.py
  lego/apps/joblistings/filters.py
Labels: enhancement, review-needed, small-fix

#2963 Make sure possible_pools are distinct
  lego/apps/events/models.py
  lego/apps/events/views.py
Labels: approved, bug-fix, ready-to-merge, small-fix

#2949 add implementation for quote sorting
  lego/apps/quotes/views.py
Labels: new-feature, approved, review-needed
