Repository webkom/lego, pull requests merged in 2023-08, with the labels that each got.

#3255 Feide verification
  lego/api/v1.py
  lego/apps/users/constants.py
  lego/apps/users/fixtures/test_users.yaml
  lego/apps/users/migrations/0040_user_student_verification_status.py
  lego/apps/users/models.py
  lego/apps/users/registrations.py
  lego/apps/users/serializers/student_confirmation.py
  lego/apps/users/tests/test_models.py
  lego/apps/users/tests/test_student_confirmation_api.py
  lego/apps/users/validators.py
  lego/apps/users/views/oidc.py
  lego/apps/users/views/student_confirmation.py
  lego/settings/base.py
  lego/settings/development.py
  lego/settings/lego.py
  lego/settings/production.py
  lego/settings/test.py
  poetry.lock
  pyproject.toml
Labels: new-feature, priority:high, future-was-2-years-ago, review-needed, need-before-2050

#3469 Fix bad cache env setting
  lego/settings/production.py
Labels: priority:high, bug-fix, small-fix, flawless

#3471 Fix bad naming of MSTCNNS
  lego/apps/users/constants.py
  lego/apps/users/models.py
  lego/apps/users/tests/test_student_confirmation_api.py
Labels: help-wanted, testing-needed, priority:high, bug-fix, review-needed

#3461 Allow unauthenticated users to view group details
  lego/apps/users/permissions.py
  lego/apps/users/tests/test_abakusgroup_api.py
Labels: review-needed, small-fix

#3472 Rename studies back to uppercase
  lego/apps/users/constants.py
  lego/apps/users/models.py
  lego/apps/users/tests/test_student_confirmation_api.py
Labels: priority:high, bug-fix, review-needed

#3481 Implement github and linkedin links on profile
  lego/apps/users/migrations/0041_user_linkedin_id_alter_user_github_username.py
  lego/apps/users/models.py
  lego/apps/users/serializers/users.py
  lego/apps/users/validators.py
Labels: in-progress, new-feature, backend, level:easy, review-needed

#3312 Implement Image Gallery Functionality & Endpoints
  lego/api/v1.py
  lego/apps/events/serializers/events.py
  lego/apps/events/views.py
  lego/apps/files/fixtures/test_files.yaml
  lego/apps/files/migrations/0005_file_save_for_use.py
  lego/apps/files/models.py
  lego/apps/files/serializers.py
  lego/apps/files/tests/test_api.py
  lego/apps/files/views.py
Labels: new-feature, approved, changes-requested, review-needed
