Repository webkom/lego, pull requests merged in 2023-04, with the labels that each got.

#3281 Implement `poetry` into project
  .flake8
  Dockerfile
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  requirements/base.txt
  requirements/black.txt
  requirements/coverage.txt
  requirements/dev.txt
  requirements/docs.txt
  requirements/flake8.txt
  requirements/isort.txt
  requirements/mypy.txt
  requirements/prod.txt
  setup.cfg
  tox.ini
Labels: new-feature, enhancement, dependencies, approved, future-was-2-years-ago

#3313 Fix docker build with poetry
  Dockerfile
Labels: priority:high, approved, ready-to-merge, small-fix

#3300 Bump channels to v4
  poetry.lock
  pyproject.toml
Labels: dependencies, review-needed

#3340 Fix DAPHNE_SERVER setting check
  lego/settings/__init__.py
Labels: backend, approved, bug-fix, small-fix

#3347 Replace dummy HTTPConsumer with a working one
  lego/apps/websockets/routing.py
Labels: backend, approved, bug-fix, small-fix

#3334 Fetch event analytics from Plausible
  lego/apps/events/views.py
  lego/settings/production.py
Labels: new-feature, approved, future-is-now, ready-to-merge
