Repository webkom/lego, pull requests merged in 2023-11, with the labels that each got.

#3515 Change penalty ignore period to start at this years last event
  lego/settings/lego.py
Labels: approved, small-fix, flawless

#3520 Individual reactions
  lego/apps/meetings/serializers.py
Labels: backend, review-needed

#3526 Fix sending announcements to meetings
  lego/apps/notifications/serializers.py
Labels: bug, bug-fix, review-needed

#3530 Fix joblistings always available despite having set a custom date
  lego/apps/joblistings/migrations/0010_alter_joblisting_visible_from.py
  lego/apps/joblistings/models.py
  lego/apps/joblistings/tests/test_joblistings_api.py
  lego/apps/joblistings/views.py
Labels: bug-fix
