Repository webkom/lego, pull requests merged in 2023-03, with the labels that each got.

#3231 Implement exporting of all company interest data to a csv file
  lego/apps/companies/constants.py
  lego/apps/companies/fixtures/test_company_interest.yaml
  lego/apps/companies/tests/test_company_interest.py
  lego/apps/companies/views.py
Labels: new-feature, review-needed

#3243 Add external mail user sofaktura@abakus.no
  lego/settings/lego.py
Labels: approved, ready-to-merge, small-fix, flawless

#3244 Validate company company name at csv export
  lego/apps/companies/views.py
Labels: approved, bug-fix, small-fix

#3220 Change author on articles from one to many
  lego/apps/articles/migrations/0011_article_authors.py
  lego/apps/articles/models.py
  lego/apps/articles/serializers.py
  lego/apps/articles/tests/test_articles_api.py
Labels: new-feature, approved, changes-requested

#3259 Merge data from "created_by" to "authors" field
  lego/apps/articles/fixtures/development_articles.yaml
  lego/apps/articles/fixtures/test_articles.yaml
  lego/apps/articles/migrations/0012_migrate_authors.py
Labels: bug-fix
