Repository webkom/lego, pull requests merged in 2023-02, with the labels that each got.

#3198 Add plausible source to weekly email links
  lego/apps/email/tasks.py
  lego/apps/email/templates/email/email/weekly_mail.html
Labels: enhancement, approved

#3206 Add "Revy" group to LDAP sync
  lego/settings/lego.py
Labels: approved, bug-fix, ready-to-merge, flawless

#3200 Improve weekly mail
  lego/apps/email/tasks.py
  lego/apps/email/templates/email/email/weekly_mail.html
Labels: enhancement, approved, ready-to-merge

#3227 Fix incorrect waiting list sorting
  lego/apps/events/views.py
Labels: priority:high, bug-fix

#3226 Edit company interest model to include more fields
  lego/apps/companies/action_handlers.py
  lego/apps/companies/constants.py
  lego/apps/companies/migrations/0027_companyinterest_bedex_comment_and_more.py
  lego/apps/companies/models.py
  lego/apps/companies/serializers.py
Labels: priority:high, review-needed

#3228 Update bedkom booking period
  lego/settings/lego.py
Labels: approved, ready-to-merge, small-fix

#3229 Fix bug sending 10+ mails to all users
  lego/apps/email/tasks.py
  lego/apps/email/tests/test_weekly_email.py
Labels: approved, bug-fix, ready-to-merge
