Repository webkom/lego, pull requests merged in 2024-11, with the labels that each got.

#3667 Fix rare race condition in event achievement task
  lego/apps/achievements/promotion.py
  lego/apps/achievements/tests/tests.py
Labels: bug-fix

#3672 Improve event page performance
  lego/apps/events/models.py
  lego/apps/events/serializers/pools.py
  lego/apps/users/serializers/users.py
  lego/settings/development.py
Labels: priority:high, approved, bug-fix

#3675 Prefetch more stuff needed in event detail page
  lego/apps/events/views.py
  lego/apps/users/serializers/users.py
Labels: backend, small-fix

#3673 Unauthed users should not see various registration counts
  lego/apps/events/fields.py
  lego/apps/events/serializers/events.py
  lego/apps/events/serializers/pools.py
Labels: approved, bug-fix, review-needed

#3677 Auto remove interest group membership for no longer students
  lego/apps/users/tests/test_grade_bump.py
  lego/utils/management/commands/bump_users.py
Labels: approved

#3678 Create db indexes for faster lookup in achievement system
  lego/apps/achievements/migrations/0002_alter_achievement_options_and_more.py
  lego/apps/achievements/models.py
  lego/apps/achievements/promotion.py
Labels: small-fix

#3665 Prevent indefinite pending unregister
  lego/apps/events/tasks.py
Labels: approved, review-needed, small-fix

#3680 Include context to event administrate serializer
  lego/apps/events/views.py
Labels: approved, bug-fix, review-needed, small-fix

#3683 Add linting rule to disallow print statements
  .flake8
  lego/apps/users/tests/test_student_confirmation_api.py
  poetry.lock
  pyproject.toml
Labels: approved, future-was-2-years-ago

#3688 fix spacing under title
  lego/apps/surveys/templates/surveys/pdf/survey_report_template.html
  lego/apps/surveys/utils/report_utils.py
Labels: enhancement, approved, review-needed
