Repository webkom/lego, pull requests merged in 2024-03, with the labels that each got.

#3566 Remove nerd import command
  lego/utils/management/commands/import_nerd.py
Labels: review-needed, chore

#3565 Extend announcement to support more filtering event
  lego/apps/events/fixtures/test_events.yaml
  lego/apps/events/models.py
  lego/apps/events/tests/test_registrations.py
  lego/apps/meetings/fixtures/test_meetings.yaml
  lego/apps/meetings/models.py
  lego/apps/notifications/fixtures/test_announcements.yaml
  lego/apps/notifications/migrations/0015_announcement_exclude_waiting_list_and_more.py
  lego/apps/notifications/models.py
  lego/apps/notifications/serializers.py
  lego/apps/notifications/tests/test_views.py
  lego/apps/restricted/tests/test_models.py
Labels: new-feature, approved, review-needed

#3570 Allow empty notification channels
  lego/apps/notifications/migrations/0016_alter_notificationsetting_channels.py
  lego/apps/notifications/models.py
Labels: approved, bug-fix, review-needed

#3564 Introduce "too late" as an event presence status
  lego/apps/events/constants.py
  lego/apps/events/migrations/0040_alter_registration_presence.py
  lego/apps/events/models.py
  lego/apps/events/serializers/registrations.py
  lego/apps/events/tests/test_penalties.py
  lego/apps/users/constants.py
  lego/apps/users/migrations/0042_penalty_type.py
  lego/apps/users/models.py
Labels: new-feature, approved, bug-fix, review-needed

#3573 Disable pagination in TagViewSet
  lego/apps/tags/tests/test_views.py
  lego/apps/tags/views.py
Labels: enhancement, approved, small-fix

#3574 Let the joblistings time filter be optional
  lego/apps/joblistings/tests/test_joblistings_api.py
  lego/apps/joblistings/views.py
Labels: new-feature, approved, review-needed, tests

#3578 Add validation for mail-list-recipients
  lego/apps/email/serializers.py
  lego/apps/email/tests/test_views.py
Labels: enhancement, approved, review-needed, tests

#3577 Extend email-user filter to add boards and ordained
  lego/apps/email/filters.py
  lego/apps/email/tests/test_views.py
  lego/apps/users/constants.py
  lego/apps/users/filters.py
  lego/apps/users/migrations/0043_alter_abakusgroup_type.py
  lego/apps/users/tests/test_abakusgroup_api.py
Labels: testing-needed, enhancement, approved, review-needed
