Repository webkom/lego, pull requests merged in 2024-10, with the labels that each got.

#3660 Remove segment tracking
  docs/stats.rst
  lego/apps/jwt/handlers.py
  lego/apps/meetings/models.py
  lego/apps/notifications/views.py
  lego/apps/oauth/authentication.py
  lego/apps/search/search.py
  lego/apps/stats/__init__.py
  lego/apps/stats/analytics_client.py
  lego/apps/stats/apps.py
  lego/apps/stats/instance_tracking.py
  lego/apps/stats/signals.py
  lego/apps/stats/utils.py
  lego/apps/surveys/tasks.py
  lego/settings/base.py
  lego/settings/celery.py
Labels: approved, chore

#3663 Update event fixtures to require feedback
  lego/apps/events/fixtures/development_events.yaml
Labels: review-needed, flawless

#3601 Prevent error when anonymous user requests allergies
  lego/apps/events/models.py
Labels: approved, small-fix

#3657 Implement The Legends and Laurels: Trophies & Triumphs (Part 1)
  lego/apps/achievements/__init__.py
  lego/apps/achievements/constants.py
  lego/apps/achievements/migrations/0001_initial.py
  lego/apps/achievements/migrations/__init__.py
  lego/apps/achievements/models.py
  lego/apps/achievements/promotion.py
  lego/apps/achievements/serializers.py
  lego/apps/achievements/tasks.py
  lego/apps/achievements/tests/__init__.py
  lego/apps/achievements/tests/tests.py
  lego/apps/achievements/verification.py
  lego/apps/events/apps.py
  lego/apps/events/fixtures/test_multiple_events.yaml
  lego/apps/events/signals.py
  lego/apps/meetings/views.py
  lego/apps/polls/views.py
  lego/apps/quotes/views.py
  lego/apps/users/serializers/users.py
  lego/settings/base.py
  lego/settings/celery.py
Labels: backend

#3666 Add new roles
  lego/apps/email/migrations/0010_alter_emaillist_group_roles.py
  lego/apps/users/constants.py
  lego/apps/users/migrations/0044_alter_membership_role_alter_membershiphistory_role.py
Labels: review-needed, small-fix
