Repository webkom/lego, pull requests merged in 2024-09, with the labels that each got.

#3633 Use DRF routing for forum thread routing
  lego/api/v1.py
  lego/apps/forums/urls.py
  lego/apps/forums/views.py
Labels: small-fix

#3638 Disallow users to give higher permission then they have
  lego/apps/users/permissions.py
  lego/apps/users/views/abakus_groups.py
Labels: priority:high, approved, bug-fix

#3637 Support report changelogs for meetings
  lego/apps/meetings/fixtures/test_meetings.yaml
  lego/apps/meetings/migrations/0010_reportchangelog.py
  lego/apps/meetings/models.py
  lego/apps/meetings/serializers.py
  lego/apps/meetings/tests/test_models.py
Labels: new-feature, approved, review-needed, tests

#3641 Fix error with registering or unregistering in local development
  lego/apps/feeds/models.py
Labels: testing-needed, approved, bug-fix, review-needed

#3529 Remove user field from survey submission read serializer
  lego/apps/surveys/serializers.py
  lego/apps/surveys/tests/test_submissions_api.py
  lego/apps/surveys/views.py
Labels: testing-needed, bug-fix, do-not-merge/WIP

#3642 Add info for calculating waiting list position within pools
  lego/apps/events/serializers/registrations.py
  lego/apps/users/serializers/users.py
Labels: backend, enhancement
