Repository webkom/lego, pull requests merged in 2024-12, with the labels that each got.

#3697 Include user reg to events in event list
  lego/apps/events/serializers/events.py
Labels: new-feature, approved, review-needed, small-fix

#3703 Fix external sync for google
  Dockerfile
  lego/apps/external_sync/utils/gsuite.py
  poetry.lock
  pyproject.toml
Labels: approved, bug-fix, future-is-now

#3705 Re-include legacy_registration_count to detailed event serializer
  lego/apps/events/serializers/events.py
Labels: approved, bug-fix, review-needed

#3699 Event serializers and views improvements
  lego/apps/events/serializers/events.py
  lego/apps/events/views.py
Labels: approved, review-needed, chore, technical-debt

#3706 Support filtering of companies
  lego/apps/companies/filters.py
  lego/apps/companies/tests/test_filters.py
  lego/apps/companies/views.py
Labels: new-feature, review-needed, tests

#3708 Add pagination, ordering to BDB
  lego/apps/companies/migrations/0030_alter_company_options.py
  lego/apps/companies/models.py
  lego/apps/companies/views.py
Labels: approved
