Repository webkom/lego, pull requests merged in 2025-04, with the labels that each got.

#3807 Move wants_thursday_event to custom field
  lego/apps/companies/constants.py
  lego/apps/companies/migrations/0034_companyinterest_wants_thursday_event.py
  lego/apps/companies/models.py
  lego/apps/companies/serializers.py
  lego/apps/companies/views.py
Labels: changes-requested, review-needed

#3825 Send websocket message on new notification
  .coveragerc
  lego/apps/comments/action_handlers.py
  lego/apps/events/action_handlers.py
  lego/apps/events/serializers/sockets.py
  lego/apps/events/websockets.py
  lego/apps/feeds/activity.py
  lego/apps/feeds/models.py
  lego/apps/feeds/serializers/__init__.py
  lego/apps/feeds/serializers/feeds.py
  lego/apps/feeds/serializers/sockets.py
  lego/apps/feeds/tests/test_feed_websockets.py
  lego/apps/feeds/utils.py
  lego/apps/feeds/views.py
  lego/apps/feeds/websockets.py
  lego/apps/meetings/action_handlers.py
  lego/apps/users/action_handlers.py
  lego/apps/websockets/consumers.py
  lego/apps/websockets/groups.py
  lego/apps/websockets/notifiers.py
  lego/apps/websockets/serializers.py
  lego/utils/json.py
Labels: backend

#3830 Fix type checking import needed in code
  lego/apps/events/websockets.py
Labels: bug-fix
