Repository webkom/lego, pull requests merged in 2025-02, with the labels that each got.

#3741 Replace HSP image
  lego/apps/surveys/templates/surveys/pdf/survey_report_template.html
  lego/apps/surveys/views.py
  lego/assets/img/bekk_short_black.svg
  lego/assets/img/netcompany.svg
Labels: review-needed, small-fix

#3740 Patch event count bug with waiting list
  lego/apps/achievements/verification.py
Labels: bug-fix

#3742 Make quotes not approvable front-end
  lego/apps/quotes/fixtures/test_quotes.yaml
  lego/apps/quotes/serializers.py
  lego/apps/quotes/tests/test_api_quotes.py
Labels: review-needed, small-fix

#3723 Implement template boolean to allow unlimited templates
  lego/apps/surveys/fixtures/test_survey_templates.yaml
  lego/apps/surveys/migrations/0013_survey_is_template_alter_survey_event.py
  lego/apps/surveys/models.py
  lego/apps/surveys/permissions.py
  lego/apps/surveys/serializers.py
  lego/apps/surveys/tests/test_templates_api.py
  lego/apps/surveys/views.py
Labels: backend
