Repository webkom/lego, pull requests merged in 2025-03, with the labels that each got.

#3759 Fixes a bug where unanswered surveys were bugged
  lego/apps/users/models.py
Labels: bug-fix

#3767 Add banner to backend
  lego/api/v1.py
  lego/apps/banners/__init__.py
  lego/apps/banners/apps.py
  lego/apps/banners/constants.py
  lego/apps/banners/migrations/0001_initial.py
  lego/apps/banners/migrations/__init__.py
  lego/apps/banners/models.py
  lego/apps/banners/permissions.py
  lego/apps/banners/serializers.py
  lego/apps/banners/tests.py
  lego/apps/banners/views.py
  lego/settings/base.py
  lego/utils/views.py
Labels: new-feature, review-needed

#3750 Implement PermissionHandler for surveys
  lego/apps/surveys/migrations/0014_alter_survey_options.py
  lego/apps/surveys/models.py
  lego/apps/surveys/permissions.py
  lego/apps/surveys/tests/test_submissions_api.py
  lego/apps/surveys/tests/test_surveys_api.py
  lego/apps/surveys/views.py
  lego/apps/users/fixtures/test_abakus_groups.py
  lego/apps/users/fixtures/test_abakus_groups.yaml
  lego/utils/views.py
Labels: review-needed, technical-debt

#3720 Revert crypt hash generation on login
  lego/api/tests/test_authentication.py
  lego/apps/users/fixtures/test_users.yaml
  lego/urls.py
Labels: review-needed

#3782 Make trophy proc instantly
  lego/apps/achievements/promotion.py
  lego/apps/users/views/users.py
Labels: small-fix

#3788 Allow non admins to list surveys and add user filter
  lego/apps/surveys/filters.py
  lego/apps/surveys/permissions.py
  lego/apps/surveys/tests/test_surveys_api.py
  lego/apps/surveys/views.py
  lego/apps/users/fixtures/test_abakus_groups.py
  lego/apps/users/fixtures/test_abakus_groups.yaml
Labels: review-needed, technical-debt

#3793 [URGENT] Restrict leader role in open groups
  lego/apps/users/permissions.py
Labels: bug-fix

#3794 Add company description to events
  lego/apps/events/migrations/0042_event_show_company_description.py
  lego/apps/events/models.py
  lego/apps/events/serializers/events.py
Labels: review-needed

#3798 Add statistics to Articles
  lego/apps/articles/tests/test_articles_api.py
  lego/apps/articles/views.py
  lego/apps/events/views.py
  lego/utils/functions.py
Labels: new-feature, review-needed

#3808 Make statistics support slugs
  lego/utils/functions.py
Labels: review-needed, small-fix

#3814 Fix plausible statistics
  lego/utils/functions.py
Labels: review-needed, small-fix
